// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ZLDLRWUdjS1gY81Zp-Zy1RXIUGRbZbg',
    appId: '1:464591743500:web:b19e8480badf2fa4ed5c29',
    messagingSenderId: '464591743500',
    projectId: 'hpci-proj',
    authDomain: 'hpci-proj.firebaseapp.com',
    storageBucket: 'hpci-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm77o9UHX270X7WjEBBSy8l8hUL532xSk',
    appId: '1:464591743500:android:7c9f3925af94237aed5c29',
    messagingSenderId: '464591743500',
    projectId: 'hpci-proj',
    storageBucket: 'hpci-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6dNDLQiMCnoS3d56RFvZxd0UU0FScAXA',
    appId: '1:464591743500:ios:5fd8ec4d76f97841ed5c29',
    messagingSenderId: '464591743500',
    projectId: 'hpci-proj',
    storageBucket: 'hpci-proj.appspot.com',
    iosBundleId: 'com.example.humanInteractionProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6dNDLQiMCnoS3d56RFvZxd0UU0FScAXA',
    appId: '1:464591743500:ios:458d4bc24d05b732ed5c29',
    messagingSenderId: '464591743500',
    projectId: 'hpci-proj',
    storageBucket: 'hpci-proj.appspot.com',
    iosBundleId: 'com.example.humanInteractionProj.RunnerTests',
  );
}
